name: fog-node-discovery
channels:
  - defaults
dependencies:
  - astroid=2.4.0
  - atomicwrites=1.4.0
  - attrs=19.3.0
  - backcall=0.2.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - cfitsio=3.470
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.5.0
  - colorama=0.4.3
  - curl=7.67.0
  - decorator=4.4.2
  - expat=2.2.9
  - fiona=1.8.13.post1
  - freexl=1.0.5
  - gdal=3.0.2
  - geopandas=0.8.1
  - geos=3.8.0
  - geotiff=1.5.1
  - hdf4=4.2.13
  - hdf5=1.10.4
  - icu=58.2
  - importlib_metadata=1.5.0
  - intel-openmp=2020.0
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - isort=4.3.21
  - jedi=0.17.2
  - jpeg=9b
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - kealib=1.4.7
  - krb5=1.16.4
  - lazy-object-proxy=1.4.3
  - libboost=1.67.0
  - libcurl=7.67.0
  - libgdal=3.0.2
  - libiconv=1.15
  - libkml=1.3.0
  - libnetcdf=4.6.1
  - libpng=1.6.37
  - libpq=11.2
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libxml2=2.9.10
  - lz4-c=1.8.1.2
  - mccabe=0.6.1
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - more-itertools=8.2.0
  - munch=2.5.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openjpeg=2.3.0
  - openssl=1.1.1h
  - packaging=20.3
  - pandas=1.0.3
  - parso=0.7.0
  - pcre=8.44
  - pickleshare=0.7.5
  - pip=20.0.2
  - pluggy=0.13.1
  - postgresql=11.2
  - proj=6.2.1
  - prompt-toolkit=3.0.7
  - py=1.8.1
  - pygments=2.7.1
  - pylint=2.5.0
  - pyparsing=2.4.7
  - pyproj=2.6.1.post1
  - pytest=5.4.1
  - python=3.7.7
  - python-dateutil=2.8.1
  - pytz=2020.1
  - pyyaml=5.3.1
  - pyzmq=19.0.2
  - rtree=0.9.4
  - scipy=1.5.2
  - setuptools=46.1.3
  - shapely=1.7.1
  - six=1.14.0
  - sqlite=3.31.1
  - tbb=2018.0.5
  - tiledb=1.6.3
  - tk=8.6.10
  - toml=0.10.0
  - tornado=6.0.4
  - traitlets=5.0.4
  - typed-ast=1.4.1
  - wcwidth=0.1.9
  - wheel=0.34.2
  - wrapt=1.11.2
  - xerces-c=3.2.3
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
      - autopep8==1.5.2
      - cycler==0.10.0
      - descartes==1.1.0
      - geographiclib==1.50
      - geopy==2.0.0
      - kiwisolver==1.2.0
      - matplotlib==3.3.2
      - pillow==7.2.0
      - pycodestyle==2.5.0
      - simpy==4.0.1
prefix: C:\Users\shube\Miniconda3\envs\fog-node-discovery
